
# Vulture summaries

```{r}
# If working offline read in the clean data

#tmp_csv <- read.csv("tmp/vulture_clean.csv", header=T)
# library(lubridate)
#tmp_csv$timestamp <- ymd_hms(tmp_csv$timestamp)

# Read RDS
#dat_shp <- readRDS("tmp/vulture_clean.RDS")
dat_shp <- vulture_stack

# Just peru
peru_shp <- dat_shp[dat_shp$location_lat<(-6),]
# Just CR
cr_shp <- dat_shp[dat_shp$location_lat>(2),]
# Just Ecuador
ec_shp <- dat_shp[dat_shp$location_lat<(2) & dat_shp$location_lat>(-6),]

# str(peru_shp)
# # Just those after that initial bout
# peru_shp_sub <- peru_shp[!(peru_shp$name %in% c("OC8","OC6","OC3","OC4","OC5","OC7","OC9","OC2","OC1","OC10")),]
# peru_tracks <- mt_track_data(peru_shp_sub)
# 
# peru_summary <- peru_tracks[, c("local_identifier", "taxon_canonical_name", "timestamp_start", "timestamp_end", "number_of_events")]
# peru_summary$timestamp_start <- ymd_hms(peru_summary$timestamp_start)
# peru_summary$timestamp_end <- ymd_hms(peru_summary$timestamp_end)
# 
# peru_summary$days <- round(as.numeric(peru_summary$timestamp_end- peru_summary$timestamp_start)/24,0)
# 
# ####
# # Subset to just the new birds in peru for the report
# track_shp <- mt_track_lines(peru_shp_sub)
# peru_summary$distance_moved_km <- as.numeric(round(st_length(track_shp)/1000,1))
# peru_summary$avg_daily_dist_km <- as.numeric(round(peru_summary$distance_moved_km/ peru_summary$days,1))
# 
# boxplot(peru_summary$avg_daily_dist_km~peru_summary$taxon_canonical_name, las=1, 
#         xlab="Species", ylab="Average daily distance per day (km)")
# 
# plot(dat$timestamp[dat$location_lat>0], dat$eobs_temperature[dat$location_lat>0],
#      pch=16, col=rgb(0,0,0,0.01), las=1)
# 
# 
# plot(dat$timestamp[dat$location_lat>0 & dat$ground_speed>4], dat$eobs_temperature[dat$location_lat>0 & dat$ground_speed>4],
#      pch=16, col=rgb(0,0,0,0.01), las=1)
# 
# # Just flying
# plot(dat$timestamp[dat$location_lat>0 & dat$ground_speed>4], dat$eobs_temperature[dat$location_lat>0 & dat$ground_speed>4],
#      pch=16, col=rgb(0,0,0,0.01), las=1)
# 
# 
# # Time of day
# 
# 
# plot(as.numeric(substr(dat$timestamp[dat$location_lat>0],12,13)), dat$eobs_temperature[dat$location_lat>0],
#      pch=16, col=rgb(0,0,0,0.01), las=1)


```

### Clean maps

#### Peru

```{r}

# Track data
tracks_tmp  <- mt_track_lines(peru_shp)
tracks_data  <- mt_track_data(peru_shp)


# First lets choose a category to colour
tracks_data$local_identifier <- factor(tracks_data$local_identifier)
col.cat <- turbo(length(levels(tracks_data$local_identifier)))
# Add it to the dataframe
tracks_data$colours <- col.cat[tracks_data$local_identifier]

ids <- tracks_data$track
i <- 1
m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS") %>%  
    addProviderTiles(providers$CartoDB.PositronNoLabels, group="Simple")


  for (i in seq(along=ids))
    {
      tmp <- tracks_tmp[tracks_tmp$track == ids[i],]
      m <- m %>%
        addPolylines(data = tmp, color = tracks_data$colours[i], group = ids[i], weight=0.5,opacity=0.5)  
    }
    
  m <- m %>%
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("Simple","OS", "Satellite"),
        overlayGroups = ids,
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 


```

#### Costa Rica

```{r}

# Track data
tracks_tmp  <- mt_track_lines(cr_shp)
tracks_data  <- mt_track_data(cr_shp)


# First lets choose a category to colour
tracks_data$local_identifier <- factor(tracks_data$local_identifier)
col.cat <- turbo(length(levels(tracks_data$local_identifier)))
# Add it to the dataframe
tracks_data$colours <- col.cat[tracks_data$local_identifier]

ids <- tracks_data$track
i <- 1
m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS") %>%  
    addProviderTiles(providers$CartoDB.PositronNoLabels, group="Simple")


  for (i in seq(along=ids))
    {
      tmp <- tracks_tmp[tracks_tmp$track == ids[i],]
      m <- m %>%
        addPolylines(data = tmp, color = tracks_data$colours[i], group = ids[i], weight=0.5,opacity=0.5)  
    }
    
  m <- m %>%
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("Simple","OS", "Satellite"),
        overlayGroups = ids,
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 

```

#### Ecuador

```{r}

# Track data
tracks_tmp  <- mt_track_lines(ec_shp)
tracks_data  <- mt_track_data(ec_shp)


# First lets choose a category to colour
tracks_data$local_identifier <- factor(tracks_data$local_identifier)
col.cat <- turbo(length(levels(tracks_data$local_identifier)))
# Add it to the dataframe
tracks_data$colours <- col.cat[tracks_data$local_identifier]

ids <- tracks_data$track
i <- 1
m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS") %>%  
    addProviderTiles(providers$CartoDB.PositronNoLabels, group="Simple")


  for (i in seq(along=ids))
    {
      tmp <- tracks_tmp[tracks_tmp$track == ids[i],]
      m <- m %>%
        addPolylines(data = tmp, color = tracks_data$colours[i], group = ids[i], weight=0.5,opacity=0.5)  
    }
   
  m <- m %>%
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("Simple","OS", "Satellite"),
        overlayGroups = ids,
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 

```

#### Summary table

```{r}
all_tracks <- mt_track_data(dat_shp)

all_summary <- all_tracks[, c("local_identifier", "taxon_canonical_name", "timestamp_start", "timestamp_end", "number_of_events")]
all_summary$timestamp_start <- ymd_hms(all_summary$timestamp_start)
all_summary$timestamp_end <- ymd_hms(all_summary$timestamp_end)

all_summary$days <- round(as.numeric(all_summary$timestamp_end- all_summary$timestamp_start)/24,0)

####
# Subset to just the new birds in all for the report
track_shp <- mt_track_lines(dat_shp)
all_summary$distance_moved_km <- as.numeric(round(st_length(track_shp)/1000,1))
all_summary$avg_daily_dist_km <- as.numeric(round(all_summary$distance_moved_km/ all_summary$days,1))
all_summary$country <- NA
all_summary[row.names(all_summary) %in% unique(ec_shp$name),]$country <- "Ecuador"
all_summary[row.names(all_summary) %in% unique(peru_shp$name),]$country <- "Peru"
all_summary[row.names(all_summary) %in% unique(cr_shp$name),]$country <- "Costa Rica"

all_summary <- all_summary[order(all_summary$country,all_summary$taxon_canonical_name,  all_summary$days, decreasing = T),]

all_summary$timestamp_start <- substr(all_summary$timestamp_start,1,10)
all_summary$timestamp_end <- substr(all_summary$timestamp_end,1,10)

all_summary <- all_summary[,c("country", "taxon_canonical_name", "local_identifier", "days", "timestamp_start",	"timestamp_end",	"number_of_events", "distance_moved_km",	"avg_daily_dist_km")]
```

```{r}

all_summary %>%
  kbl(row.names=F) %>%
  kable_styling()  %>%
  row_spec(which(all_summary$taxon_canonical_name == "Sarcoramphus papa"), background = "#c994c7bb")%>%
  row_spec(which(all_summary$taxon_canonical_name == "Coragyps atratus"), background = "#bdbdbd")  %>%
   row_spec(which(all_summary$taxon_canonical_name == "Cathartes melambrotus"), background = "#ffeda0")  %>%
     row_spec(which(all_summary$taxon_canonical_name == "Cathartes aura"), background = "#fc9272")  %>%
  kableExtra::scroll_box(width = "100%") 

```

#### Tags still functioning by country and species

Any tag reporting in the last thirty days is classed as working. 


```{r}
tmp <- table(all_summary$country, all_summary$taxon_canonical_name, (interval(ymd_hms(paste(all_summary$timestamp_end, "00:00:00")), Sys.time()) %/% days(1))<30)

tmp <- as.data.frame(tmp)
colnames(tmp) <- c("country", "species", "functioning", "freq")
d1 <- tmp[tmp$functioning==TRUE,]
d1$functioning <- NULL
colnames(d1) <- c("country","species","working")
d1$not_working <- tmp$freq[tmp$functioning==FALSE]

# Remove double zeros
d1 <- d1[!(d1$working==0 & d1$not_working==0),]
d1 <- d1[order(d1$country, d1$species),]
d1$percentage_working <- round(((d1$working)/(d1$working+ d1$not_working)*100),1)

d1 %>%
  kbl(row.names=F) %>%
  kable_styling() %>%
  kableExtra::scroll_box(width = "100%") 

```







