# Mammal Tracking

When tracking mammals it is good to understand their home range, and where they have been in the preceeding weeks.

For each individual we prodice a lifetime heatmap, and a last 4 weeks heatmap - all from cleaned data. 

### Juancito

**LIFETIME**


```{r, mt_1, message=F, warning=F}
m2 = mt_as_move2(clean_mammal[[1]], track_id_columna = tmp_mammal$name[1])
dat_lines <- m2 %>%
  mt_track_lines()

bg <- st_read("landmass.shp")
# make a fishnet grid over the data
grd <- st_make_grid(dat_lines, n = 100)
# visualize the grid
#plot(grd)


index <- which(lengths(st_intersects(grd, m2)) > 0)
# subset the grid to make a fishnet
fishnet <- grd[index]

# visualize the fishnet
#plot(fishnet)

test <- fishnet %>%   
  st_as_sf() %>% # cast to sf
  mutate(grid_id = row_number()) %>% # create unique ID
  st_join(m2) %>% # join the species dataset
  group_by(grid_id) %>% # group by the grid id
  count() 

tmp <- st_as_sf(test)

tmp$log.n <- log(tmp$n + 1)

ii <- cut(tmp$n, breaks = seq(min(tmp$n), max(tmp$n), len = 100), 
          include.lowest = TRUE)
## Use bin indices, ii, to select color from vector of n-1 equally spaced colors
colors <- inferno(99)[ii]

col_dat <- data.frame(values=seq(min(tmp$n), max(tmp$n), len = 100), colours=inferno(100))

# IF not using log
col_dat$values_obs <- round(col_dat$values,0)

# If using log
#col_dat$values_obs <- round(exp(col_dat$values),0)


m <- leaflet(tmp) %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS")  %>% 
  addPolylines(data = dat_lines,
                   #color="#FF10F0",
                   weight = 1,#opacity = 0.6,
                   # hover label
                   label = dat_lines$local_identifier, group="Track") %>%   
  addPolygons(stroke=F, color=colors, fillOpacity=1, label=tmp$n, group = "Raster") 
#?addPolygons  
m <- m %>%
      addLegend(position= "topright", colors=col_dat$colours[c(1,10,20,30,40,50,60,70,80,90,100)], 
                labels=c(1,col_dat$values_obs[c(10,20,30,40,50,60,70,80,90,100)]) ,opacity = 0.7, title = "point density") %>%    
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("OS","Satellite"),
        overlayGroups = c("Raster", "Track"),
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 



```


**LAST MONTH**

```{r mt_2, message=F, warning=F}
t <- Sys.time()
sub_dat <- m2[m2$timestamp > (t - ddays(31)),]
dat_lines <- sub_dat %>%
  mt_track_lines()


# Connect the dots
lines <- sub_dat
lines %<>% group_by(track) %>%
  slice(rep(1:n(), each = 2)) %>%
  slice(-c(1, n())) %>%
  mutate(linegroup = lapply(1:(n()/2), function(x) rep(x, 2)) %>% unlist) %>% 
  ungroup %>%
  group_by(linegroup) %>%
  st_as_sf(coords = c("Long","Lat"), crs = 4326, remove = F) %>%
  summarize( do_union = F) %>%
  st_cast("LINESTRING")

# ADdthe timestamps and colour  
lines$timestamp <- sub_dat$timestamp[2:nrow(sub_dat)]
colfunc <- colorRampPalette(c("blue", "red"))
lines$col <- colfunc(nrow(lines))
  #plot(st_geometry(lines), col=lines$col)  
  # Plot

  
  
  # ggplot(data = sub_dat)+
#   geom_sf(aes(color = `timestamp`))+
#   scale_color_gradient(name = "timestamp", position="bottom" , low = "blue", high = "red")+
#   geom_sf(data = lines, aes(color =col ))+#, aes(color = numeric(points$Time[1:(length(points$Time)-1)])))+ #did not work
#   

lines

m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS")  %>% 
  addPolylines(data = lines,
                   color=lines$col,
                   weight = 2,#opacity = 0.6,
                   # hover label
                   label = lines$timestamp,
                    group="Track") %>%
        # The last point
        addMarkers(lng=last(sub_dat$location_long),
                         lat=last(sub_dat$location_lat), 
                         popup=paste(last(sub_dat$name),
                                     "<br>Time:",last(sub_dat$timestamp),
                                     "<br>Long:",last(sub_dat$location_long),
                                     "<br>Lat:",last(sub_dat$location_lat)),
                   icon = iconSet["bairdii"]) %>% 
      addLegend(position= "topright", colors=lines$col[c(1,round(nrow(lines)/2, 0),nrow(lines))], 
                labels=substr(lines$timestamp[c(1,round(nrow(lines)/2, 0),nrow(lines))],1,11) ,opacity = 0.7, title = "Date") %>%    
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("OS","Satellite"),
        overlayGroups = c("Track"),
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 

```

### Tuva

**LIFETIME**


```{r, mt_3, message=F, warning=F}
m2 = mt_as_move2(clean_mammal[[2]], track_id_columna = tmp_mammal$name[2])
dat_lines <- m2 %>%
  mt_track_lines()

bg <- st_read("landmass.shp")
# make a fishnet grid over the data
grd <- st_make_grid(dat_lines, n = 80)
# visualize the grid
#plot(grd)


index <- which(lengths(st_intersects(grd, m2)) > 0)
# subset the grid to make a fishnet
fishnet <- grd[index]

# visualize the fishnet
#plot(fishnet)

test <- fishnet %>%   
  st_as_sf() %>% # cast to sf
  mutate(grid_id = row_number()) %>% # create unique ID
  st_join(m2) %>% # join the species dataset
  group_by(grid_id) %>% # group by the grid id
  count() 

tmp <- st_as_sf(test)

tmp$log.n <- log(tmp$n + 1)

ii <- cut(tmp$n, breaks = seq(min(tmp$n), max(tmp$n), len = 100), 
          include.lowest = TRUE)
## Use bin indices, ii, to select color from vector of n-1 equally spaced colors
colors <- inferno(99)[ii]

col_dat <- data.frame(values=seq(min(tmp$n), max(tmp$n), len = 100), colours=inferno(100))

# IF not using log
col_dat$values_obs <- round(col_dat$values,0)

# If using log
#col_dat$values_obs <- round(exp(col_dat$values),0)


m <- leaflet(tmp) %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS")  %>% 
  addPolylines(data = dat_lines,
                   #color="#FF10F0",
                   weight = 1,#opacity = 0.6,
                   # hover label
                   label = dat_lines$local_identifier, group="Track") %>%   
  addPolygons(stroke=F, color=colors, fillOpacity=1, label=tmp$n, group = "Raster") 
#?addPolygons  
m <- m %>%
      addLegend(position= "topright", colors=col_dat$colours[c(1,10,20,30,40,50,60,70,80,90,100)], 
                labels=c(1,col_dat$values_obs[c(10,20,30,40,50,60,70,80,90,100)]) ,opacity = 0.7, title = "point density") %>%    
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("OS","Satellite"),
        overlayGroups = c("Raster", "Track"),
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 



```


**LAST MONTH**

```{r mt_4, message=F, warning=F}
t <- Sys.time()
sub_dat <- m2[m2$timestamp > (t - ddays(31)),]
dat_lines <- sub_dat %>%
  mt_track_lines()


# Connect the dots
lines <- sub_dat
lines %<>% group_by(track) %>%
  slice(rep(1:n(), each = 2)) %>%
  slice(-c(1, n())) %>%
  mutate(linegroup = lapply(1:(n()/2), function(x) rep(x, 2)) %>% unlist) %>% 
  ungroup %>%
  group_by(linegroup) %>%
  st_as_sf(coords = c("Long","Lat"), crs = 4326, remove = F) %>%
  summarize( do_union = F) %>%
  st_cast("LINESTRING")

# ADdthe timestamps and colour  
lines$timestamp <- sub_dat$timestamp[2:nrow(sub_dat)]
colfunc <- colorRampPalette(c("blue", "red"))
lines$col <- colfunc(nrow(lines))
  #plot(st_geometry(lines), col=lines$col)  
  # Plot

  
  
  # ggplot(data = sub_dat)+
#   geom_sf(aes(color = `timestamp`))+
#   scale_color_gradient(name = "timestamp", position="bottom" , low = "blue", high = "red")+
#   geom_sf(data = lines, aes(color =col ))+#, aes(color = numeric(points$Time[1:(length(points$Time)-1)])))+ #did not work
#   

lines

m <- leaflet() %>%
  # Add a satellite image layer
  addProviderTiles(providers$Esri.WorldImagery, group="Satellite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group="OS")  %>% 
  addPolylines(data = lines,
                   color=lines$col,
                   weight = 2,#opacity = 0.6,
                   # hover label
                   label = lines$timestamp,
                    group="Track") %>%
        # The last point
        addMarkers(lng=last(sub_dat$location_long),
                         lat=last(sub_dat$location_lat), 
                         popup=paste(last(sub_dat$name),
                                     "<br>Time:",last(sub_dat$timestamp),
                                     "<br>Long:",last(sub_dat$location_long),
                                     "<br>Lat:",last(sub_dat$location_lat)),
                   icon = iconSet["bairdii"]) %>% 
      addLegend(position= "topright", colors=lines$col[c(1,round(nrow(lines)/2, 0),nrow(lines))], 
                labels=substr(lines$timestamp[c(1,round(nrow(lines)/2, 0),nrow(lines))],1,11) ,opacity = 0.7, title = "Date") %>%    
      addScaleBar(position="topleft", 
                  options=scaleBarOptions(maxWidth = 100, metric = TRUE, imperial = FALSE, updateWhenIdle = TRUE)) %>%
      addLayersControl(
        baseGroups = c("OS","Satellite"),
        overlayGroups = c("Track"),
        options = layersControlOptions(collapsed = FALSE)
      ) %>%
  addFullscreenControl()
  
m 

```


